### ISSUE TITLE
Could not pass event CreatureSpawnEvent to Server v1.0.0

### ISSUE THREAD

**Issue by storycraft** [story-network/story-plugin#9]
duplicated attribute applying

**Comment by storycraft** [comment]
Partial logs

`
Could not pass event CreatureSpawnEvent to Server v1.0.0
java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
        at net.minecraft.server.v1_14_R1.AttributeModifiable.addModifier(SourceFile:89) ~[server.jar:git-Paper-225]
        at org.bukkit.craftbukkit.v1_14_R1.attribute.CraftAttributeInstance.addModifier(CraftAttributeInstance.java:49) ~[server.jar:git-Paper-225]
        at com.storycraft.mod.season3.Season3MiniPlugin.onEntitySpawn(Season3MiniPlugin.java:164) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1997.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[server.jar:git-Paper-225]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[server.jar:git-Paper-225]
...
`

**Comment by storycraft** [comment]
Fixed
